### ISSUE TITLE
Set up boilerplate template

### ISSUE THREAD

**Issue by nashetty** [SchoolOfCode/bc16-final-projects-team-large-language-mavericks#12]
Create an initial commit that will include the boilerplate code from the selected template.

Acceptance critera:
-Template selected
-added to team repo
-deployed somewhere (vercel)

**Comment by Ludwig-J** [comment]
Complete. repo has the template and it is deployed at [https://soc-llm.vercel.app/](https://soc-llm.vercel.app/)
