### ISSUE TITLE
Understand basics of how KV database works

### ISSUE THREAD

**Issue by nashetty** [SchoolOfCode/bc16-final-projects-team-large-language-mavericks#15]
Our chosen app is using Vercel KV to log users in and store chat history. Understand how this works and what commands need to be used to update any data.

Acceptance criteria:
- successfully query the database
- successfully change the data for an existing key

**Comment by Ludwig-J** [comment]
Basics of KV database understood. Basic commands key * , HGETALL, HSET.    [https://redis.io/docs/latest/commands/hgetall/](https://redis.io/docs/latest/commands/hgetall/ )  [https://redis.io/docs/latest/commands/hset/](https://redis.io/docs/latest/commands/hset/)
