### ISSUE TITLE
Ceate a Hifidelity wireframe with new design

### ISSUE THREAD

**Issue by Ludwig-J** [SchoolOfCode/bc16-final-projects-team-large-language-mavericks#17]
new design for chatbot.

Acceptance critera:
-use figma to make a hifidelity wireframe of new design

**Comment by nashetty** [comment]
Hi-Fi wireframe has been updated and finalised.


![Image](https://github.com/SchoolOfCode/bc16-final-projects-team-large-language-mavericks/assets/110870202/2dd9f930-f1e9-41c5-9961-6f32814a5aea)
